const data = [
    {
        id: 1,
        blog_img: "https://images.unsplash.com/photo-1440778303588-435521a205bc?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1950&q=80",
        your_name: "Foulcher Nathanil",
        your_img: "https://i.ibb.co/hLbFK2c/Capture.png",
        date: "May 22, 2021",
        blog_title: "Lenovo's smarter devices stoke professional passions",
        blog_title_2: "Lenovo's smarter devices stoke professional passions",
        total_react: "3.4k",
        total_comment: "11",
        description:"Lorem, ipsum dolor sit amet consectetur adipisicing elit. Exercitationem voluptatibus explicabo ipsam sunt dolorum quas quo harum voluptatem minus obcaecati cupiditate esse libero molestiae tempora ipsa, laborum itaque? Laboriosam provident porro in mollitia suscipit repellat, quo doloribus eum earum beatae eaque quibusdam cum dolorum nulla ullam non corporis quae officia optio? Illo, numquam dolorum consequuntur quidem recusandae officiis provident dolore eius temporibus quae, animi rem nisi. Modi numquam debitis at corporis saepe? Maxime, architecto natus beatae laudantium repudiandae at commodi! Adipisci sit nostrum fugit animi, nesciunt amet, natus laboriosam libero ullam cupiditate a, excepturi reiciendis fuga accusantium tempore rem architecto."
    },
    {
        id: 2,
        blog_img: "https://images.unsplash.com/photo-1489753735160-2cbf3d9006d4?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1050&q=80",
        your_name: "Falconar Anges",
        your_img: "https://i.ibb.co/cQ4phmV/Capture.png",
        date: "May 20, 2021",
        blog_title: "How Ai Teams are benifiting the littlist of",
        blog_title_2: "How Ai Teams are benifiting the littlist of Man",
        total_react: "3.0k",
        total_comment: "13",
        description:"Lorem, ipsum dolor sit amet consectetur adipisicing elit. Exercitationem voluptatibus explicabo ipsam sunt dolorum quas quo harum voluptatem minus obcaecati cupiditate esse libero molestiae tempora ipsa, laborum itaque? Laboriosam provident porro in mollitia suscipit repellat, quo doloribus eum earum beatae eaque quibusdam cum dolorum nulla ullam non corporis quae officia optio? Illo, numquam dolorum consequuntur quidem recusandae officiis provident dolore eius temporibus quae, animi rem nisi. Modi numquam debitis at corporis saepe? Maxime, architecto natus beatae laudantium repudiandae at commodi! Adipisci sit nostrum fugit animi, nesciunt amet, natus laboriosam libero ullam cupiditate a, excepturi reiciendis fuga accusantium tempore rem architecto."
    },
    {
        id: 3,
        blog_img: "https://images.unsplash.com/photo-1418854982207-12f710b74003?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1000&q=80",
        your_name: "Falconar Anges",
        your_img: "https://i.ibb.co/cQ4phmV/Capture.png",
        date: "May 18, 2021",
        blog_title: "DRYer and TV Host Trisha Hersberger's journey throu",
        blog_title_2: "DRYer and TV Host Trisha Hersberger's journey through",
        total_react: "222",
        total_comment: "33",
        description:"Lorem, ipsum dolor sit amet consectetur adipisicing elit. Exercitationem voluptatibus explicabo ipsam sunt dolorum quas quo harum voluptatem minus obcaecati cupiditate esse libero molestiae tempora ipsa, laborum itaque? Laboriosam provident porro in mollitia suscipit repellat, quo doloribus eum earum beatae eaque quibusdam cum dolorum nulla ullam non corporis quae officia optio? Illo, numquam dolorum consequuntur quidem recusandae officiis provident dolore eius temporibus quae, animi rem nisi. Modi numquam debitis at corporis saepe? Maxime, architecto natus beatae laudantium repudiandae at commodi! Adipisci sit nostrum fugit animi, nesciunt amet, natus laboriosam libero ullam cupiditate a, excepturi reiciendis fuga accusantium tempore rem architecto."
    },
    {
        id: 4,
        blog_img: "https://images.unsplash.com/photo-1518609878373-06d740f60d8b?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1000&q=80",
        your_name: "Tousy Vita",
        your_img: "https://i.ibb.co/4Z5nKyV/Capture.png",
        date: "May 20, 2021",
        blog_title: "Take a 3D tour through a Microsoft datacenter",
        blog_title_2: "Take a 3D tour through a Microsoft datacenter",
        total_react: "3.3k",
        total_comment: "20",
        description:"Lorem, ipsum dolor sit amet consectetur adipisicing elit. Exercitationem voluptatibus explicabo ipsam sunt dolorum quas quo harum voluptatem minus obcaecati cupiditate esse libero molestiae tempora ipsa, laborum itaque? Laboriosam provident porro in mollitia suscipit repellat, quo doloribus eum earum beatae eaque quibusdam cum dolorum nulla ullam non corporis quae officia optio? Illo, numquam dolorum consequuntur quidem recusandae officiis provident dolore eius temporibus quae, animi rem nisi. Modi numquam debitis at corporis saepe? Maxime, architecto natus beatae laudantium repudiandae at commodi! Adipisci sit nostrum fugit animi, nesciunt amet, natus laboriosam libero ullam cupiditate a, excepturi reiciendis fuga accusantium tempore rem architecto."
    },
    {
        id: 5,
        blog_img: "https://images.unsplash.com/photo-1448518340475-e3c680e9b4be?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1951&q=80",
        your_name: "Fones Mimi",
        your_img: "https://i.ibb.co/PFJ8XNW/Capture.png",
        date: "May 19, 2021",
        blog_title: "Peopla who inspired us in 2019",
        blog_title_2: "Peopla who inspired us in 2019",
        total_react: "3.6k",
        total_comment: "9",
        description:"Lorem, ipsum dolor sit amet consectetur adipisicing elit. Exercitationem voluptatibus explicabo ipsam sunt dolorum quas quo harum voluptatem minus obcaecati cupiditate esse libero molestiae tempora ipsa, laborum itaque? Laboriosam provident porro in mollitia suscipit repellat, quo doloribus eum earum beatae eaque quibusdam cum dolorum nulla ullam non corporis quae officia optio? Illo, numquam dolorum consequuntur quidem recusandae officiis provident dolore eius temporibus quae, animi rem nisi. Modi numquam debitis at corporis saepe? Maxime, architecto natus beatae laudantium repudiandae at commodi! Adipisci sit nostrum fugit animi, nesciunt amet, natus laboriosam libero ullam cupiditate a, excepturi reiciendis fuga accusantium tempore rem architecto."
    },
    {
        id: 6,
        blog_img: "https://images.pexels.com/photos/4397925/pexels-photo-4397925.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
        your_name: "Pillifant Vern",
        your_img: "https://i.ibb.co/D9FRHKY/Capture.png",
        date: "May 19, 2021",
        blog_title: "How Architects visualize design for world's bi",
        blog_title_2: "How Architects visualize design for world's biggest",
        total_react: "3.1k",
        total_comment: "13",
        description:"Lorem, ipsum dolor sit amet consectetur adipisicing elit. Exercitationem voluptatibus explicabo ipsam sunt dolorum quas quo harum voluptatem minus obcaecati cupiditate esse libero molestiae tempora ipsa, laborum itaque? Laboriosam provident porro in mollitia suscipit repellat, quo doloribus eum earum beatae eaque quibusdam cum dolorum nulla ullam non corporis quae officia optio? Illo, numquam dolorum consequuntur quidem recusandae officiis provident dolore eius temporibus quae, animi rem nisi. Modi numquam debitis at corporis saepe? Maxime, architecto natus beatae laudantium repudiandae at commodi! Adipisci sit nostrum fugit animi, nesciunt amet, natus laboriosam libero ullam cupiditate a, excepturi reiciendis fuga accusantium tempore rem architecto."
    },
    {
        id: 7,
        blog_img: "https://images.unsplash.com/photo-1504992963429-56f2d62fbff0?ixid=MnwxMjA3fDB8MHxzZWFyY2h8ODN8fHRlY2hub2xvZ3l8ZW58MHx8MHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1000&q=80",
        your_name: "Falconar Anges",
        your_img: "https://i.ibb.co/cQ4phmV/Capture.png",
        date: "May 20, 2021",
        blog_title: "Mind games: How gaming can play a positive role in ment",
        blog_title_2: "Mind games: How gaming can play a positive role in mental",
        total_react: "1.30k",
        total_comment: "18",
        description:"Lorem, ipsum dolor sit amet consectetur adipisicing elit. Exercitationem voluptatibus explicabo ipsam sunt dolorum quas quo harum voluptatem minus obcaecati cupiditate esse libero molestiae tempora ipsa, laborum itaque? Laboriosam provident porro in mollitia suscipit repellat, quo doloribus eum earum beatae eaque quibusdam cum dolorum nulla ullam non corporis quae officia optio? Illo, numquam dolorum consequuntur quidem recusandae officiis provident dolore eius temporibus quae, animi rem nisi. Modi numquam debitis at corporis saepe? Maxime, architecto natus beatae laudantium repudiandae at commodi! Adipisci sit nostrum fugit animi, nesciunt amet, natus laboriosam libero ullam cupiditate a, excepturi reiciendis fuga accusantium tempore rem architecto."
    },
    {
        id: 8,
        blog_img: "https://images.unsplash.com/photo-1465310477141-6fb93167a273?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1950&q=80",
        your_name: "Pillifant Vern",
        your_img: "https://i.ibb.co/D9FRHKY/Capture.png",
        date: "May 19, 2021",
        blog_title: "Microsoft announces a five year commitment to cre",
        blog_title_2: "Microsoft announces a five year commitment to create",
        total_react: "2.6k",
        total_comment: "19",
        description:"Lorem, ipsum dolor sit amet consectetur adipisicing elit. Exercitationem voluptatibus explicabo ipsam sunt dolorum quas quo harum voluptatem minus obcaecati cupiditate esse libero molestiae tempora ipsa, laborum itaque? Laboriosam provident porro in mollitia suscipit repellat, quo doloribus eum earum beatae eaque quibusdam cum dolorum nulla ullam non corporis quae officia optio? Illo, numquam dolorum consequuntur quidem recusandae officiis provident dolore eius temporibus quae, animi rem nisi. Modi numquam debitis at corporis saepe? Maxime, architecto natus beatae laudantium repudiandae at commodi! Adipisci sit nostrum fugit animi, nesciunt amet, natus laboriosam libero ullam cupiditate a, excepturi reiciendis fuga accusantium tempore rem architecto."
    },
    {
        id: 9,
        blog_img: "https://images.unsplash.com/photo-1581122584612-713f89daa8eb?ixid=MnwxMjA3fDB8MHxwaG90by1yZWxhdGVkfDIwfHx8ZW58MHx8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=1000&q=80",
        your_name: "Pillifant Vern",
        your_img: "https://i.ibb.co/D9FRHKY/Capture.png",
        date: "May 19, 2021",
        blog_title: "360-degree video: How Microsoft deployed a",
        blog_title_2: "360-degree video: How Microsoft deployed awite theme",
        total_react: "773",
        total_comment: "14",
        description:"Lorem, ipsum dolor sit amet consectetur adipisicing elit. Exercitationem voluptatibus explicabo ipsam sunt dolorum quas quo harum voluptatem minus obcaecati cupiditate esse libero molestiae tempora ipsa, laborum itaque? Laboriosam provident porro in mollitia suscipit repellat, quo doloribus eum earum beatae eaque quibusdam cum dolorum nulla ullam non corporis quae officia optio? Illo, numquam dolorum consequuntur quidem recusandae officiis provident dolore eius temporibus quae, animi rem nisi. Modi numquam debitis at corporis saepe? Maxime, architecto natus beatae laudantium repudiandae at commodi! Adipisci sit nostrum fugit animi, nesciunt amet, natus laboriosam libero ullam cupiditate a, excepturi reiciendis fuga accusantium tempore rem architecto."
    },
    {
        id: 10,
        blog_img: "https://images.unsplash.com/photo-1606490114832-d41056bdca34?ixid=MnwxMjA3fDB8MHxzZWFyY2h8MzY1fHxnYW1pbmd8ZW58MHx8MHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1000&q=80",
        your_name: "Foulcher Nathanil",
        your_img: "https://i.ibb.co/hLbFK2c/Capture.png",
        date: "May 19, 2021",
        blog_title: "To cool datacenter servers, Microsoft turns to boil",
        blog_title_2: "To cool datacenter servers, Microsoft turns to boiling",
        total_react: "1.4k",
        total_comment: "39",
        description:"Lorem, ipsum dolor sit amet consectetur adipisicing elit. Exercitationem voluptatibus explicabo ipsam sunt dolorum quas quo harum voluptatem minus obcaecati cupiditate esse libero molestiae tempora ipsa, laborum itaque? Laboriosam provident porro in mollitia suscipit repellat, quo doloribus eum earum beatae eaque quibusdam cum dolorum nulla ullam non corporis quae officia optio? Illo, numquam dolorum consequuntur quidem recusandae officiis provident dolore eius temporibus quae, animi rem nisi. Modi numquam debitis at corporis saepe? Maxime, architecto natus beatae laudantium repudiandae at commodi! Adipisci sit nostrum fugit animi, nesciunt amet, natus laboriosam libero ullam cupiditate a, excepturi reiciendis fuga accusantium tempore rem architecto."
    },
    {
        id: 11,
        blog_img: "https://images.unsplash.com/photo-1587381420844-7bc5f4feec02?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1000&q=80",
        your_name: "Pillifant Vern",
        your_img: "https://i.ibb.co/D9FRHKY/Capture.png",
        date: "May 18, 2021",
        blog_title: "Xbox connect people to help through Crisis text line and",
        blog_title_2: "Xbox connect people to help through Crisis text line and height",
        total_react: "913",
        total_comment: "2",
        description:"Lorem, ipsum dolor sit amet consectetur adipisicing elit. Exercitationem voluptatibus explicabo ipsam sunt dolorum quas quo harum voluptatem minus obcaecati cupiditate esse libero molestiae tempora ipsa, laborum itaque? Laboriosam provident porro in mollitia suscipit repellat, quo doloribus eum earum beatae eaque quibusdam cum dolorum nulla ullam non corporis quae officia optio? Illo, numquam dolorum consequuntur quidem recusandae officiis provident dolore eius temporibus quae, animi rem nisi. Modi numquam debitis at corporis saepe? Maxime, architecto natus beatae laudantium repudiandae at commodi! Adipisci sit nostrum fugit animi, nesciunt amet, natus laboriosam libero ullam cupiditate a, excepturi reiciendis fuga accusantium tempore rem architecto."
    },
    {
        id: 12,
        blog_img: "https://images.pexels.com/photos/347141/pexels-photo-347141.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
        your_name: "Birrell Chariot",
        your_img: "https://i.ibb.co/cCdChBM/Capture.png",
        date: "May 17, 2021",
        blog_title: "WNBA's Sabrina lonescu teams up with Xbox to",
        blog_title_2: "WNBA's Sabrina lonescu teams up with Xbox to connect",
        total_react: "1.9k",
        total_comment: "27",
        description:"Lorem, ipsum dolor sit amet consectetur adipisicing elit. Exercitationem voluptatibus explicabo ipsam sunt dolorum quas quo harum voluptatem minus obcaecati cupiditate esse libero molestiae tempora ipsa, laborum itaque? Laboriosam provident porro in mollitia suscipit repellat, quo doloribus eum earum beatae eaque quibusdam cum dolorum nulla ullam non corporis quae officia optio? Illo, numquam dolorum consequuntur quidem recusandae officiis provident dolore eius temporibus quae, animi rem nisi. Modi numquam debitis at corporis saepe? Maxime, architecto natus beatae laudantium repudiandae at commodi! Adipisci sit nostrum fugit animi, nesciunt amet, natus laboriosam libero ullam cupiditate a, excepturi reiciendis fuga accusantium tempore rem architecto."
    },
]